# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "925cc071d9251e32f4bac04a2677291b"
name = "Itme-Theme"
application_url = "https://layers-sierra-king-completed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "brandons-test-development-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://layers-sierra-king-completed.trycloudflare.com/auth/callback",
  "https://layers-sierra-king-completed.trycloudflare.com/auth/shopify/callback",
  "https://layers-sierra-king-completed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
