# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "42da0f9e6dc39279228363942e7437d6"
name = "Items to Colors"
application_url = "https://apt-industrial-potato-cooperation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lloyddemodevstore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://apt-industrial-potato-cooperation.trycloudflare.com/auth/callback",
  "https://apt-industrial-potato-cooperation.trycloudflare.com/auth/shopify/callback",
  "https://apt-industrial-potato-cooperation.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
